# Generated by Django 6.0.5 on 2026-08-10 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_projecttype_project_price_factor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(verbose_name='قیمت پایه سفارشات')),
                ('price_reg_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'قیمت پایه سفارشات',
                'verbose_name_plural': 'قیمت پایه سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materal_name', models.CharField(max_length=20, verbose_name='نام جنس')),
                ('price_factor', models.IntegerField(verbose_name='ضریب قیمت جنس')),
                ('price_reg_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'جنس مصرفی',
                'verbose_name_plural': 'اجناس مصرفی',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20, verbose_name='عنوان وضعیت')),
            ],
            options={
                'verbose_name': 'وضعیت سفارش',
                'verbose_name_plural': 'وضعیت های سفارش',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=20, verbose_name='عنوان سفارش')),
                ('orderer_name', models.CharField(max_length=20, verbose_name='نام مشتری')),
                ('orderer_family', models.CharField(max_length=20, verbose_name='نام خانوادگی مشتری')),
                ('orderer_phone', models.CharField(max_length=11, verbose_name='شماره تماس مشتری')),
                ('orderer_address', models.CharField(max_length=40, verbose_name='آدرس مشتری')),
                ('order_metrics', models.IntegerField(verbose_name='متراژ')),
                ('order_unit', models.IntegerField(verbose_name='تعداد سفارش')),
                ('order_reg_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت سفارش')),
                ('order_end_date', models.DateField(verbose_name='تاریخ اتمام پروژه')),
                ('order_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.manager', verbose_name='مجری پروژه')),
                ('order_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.material', verbose_name='جنس مصرفی')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projecttype', verbose_name='نوع سفارش')),
                ('orderer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سفارش دهنده')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus', verbose_name='وضعیت سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
