# Generated by Django 6.0.5 on 2026-08-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('project', '0003_projecttype_project_price_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام پروژه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.manager', verbose_name='مجری پروژه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus', verbose_name='وضعیت سفارش'),
        ),
    ]
