# Generated by Django 6.0.5 on 2026-08-04 08:10

import apps.blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=80, verbose_name='عنوان مقاله')),
                ('article_main_picture', models.FileField(upload_to='attachments/articles', verbose_name='تصویر اصلی')),
                ('article_abstract', models.TextField(verbose_name='خلاصه مقاله')),
                ('article_text', models.TextField(verbose_name='متن مقاله')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالی')),
                ('slug', models.SlugField(default='defult', verbose_name='شناسه')),
                ('views', models.IntegerField(verbose_name='تعداد لایک ها')),
                ('main_file', models.FileField(default='', upload_to='attachments/articles/files', verbose_name='فایل مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه های مقاله',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام نویسنده')),
                ('family', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('slug', models.SlugField(verbose_name='شناسه')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=20, verbose_name='کلیدواژه')),
            ],
            options={
                'verbose_name': 'کلیدواژه',
                'verbose_name_plural': 'کلیدواژه ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_picture', models.FileField(upload_to=apps.blog.models.upload_gallery_image)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article')),
            ],
            options={
                'verbose_name': 'گالری مقاله',
                'verbose_name_plural': 'گالری مقاله',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.articlegroup', verbose_name='گروه مقاله'),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('user_liked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='blog.keyword', verbose_name='کلیدواژه ها'),
        ),
    ]
