# Generated by Django 6.0.5 on 2026-08-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=20, verbose_name='نام')),
                ('manager_family', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('manager_degree', models.CharField(max_length=10, verbose_name='مدرک فنی یا تحصیلی')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('manager_phone', models.IntegerField(max_length=11, verbose_name='شماره تلفن')),
                ('manager_slug', models.SlugField(verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'مدیر پروژه',
                'verbose_name_plural': 'مدیران پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=15, verbose_name='نوع پروژه')),
            ],
            options={
                'verbose_name': 'نوع پروژه',
                'verbose_name_plural': 'انواع پروژه',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=60, verbose_name='عنوان پروژه')),
                ('project_detail', models.TextField(verbose_name='توضیحات پروژه')),
                ('project_price', models.IntegerField(verbose_name='قیمت تمام شده')),
                ('project_start_date', models.DateField(verbose_name='تاریخ شروع پروژه')),
                ('project_end_date', models.DateField(verbose_name='تاریخ پایان پروژه')),
                ('project_picture', models.ImageField(upload_to='', verbose_name='تصویر اصلی پروژه')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نمایش')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.manager', verbose_name='مدیر پروژه')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projecttype', verbose_name='نوع پروژه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
