# Generated by Django 6.0.5 on 2026-08-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_degree',
            field=models.CharField(max_length=10, verbose_name='عنوان فنی یا تحصیلی'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_phone',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_price',
            field=models.CharField(max_length=15, verbose_name='قیمت تمام شده'),
        ),
    ]
