# Generated by Django 6.0.5 on 2026-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_manager_manager_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='project_price_factor',
            field=models.IntegerField(default=1, verbose_name='ضریب قیمت'),
        ),
    ]
