# Generated by Django 6.0.5 on 2026-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='نام اختصاری شرکت')),
                ('company_full_name', models.CharField(max_length=50, verbose_name='نام کامل شرکت')),
                ('company_slogan', models.CharField(max_length=100, verbose_name='شعار شرکت')),
                ('company_description', models.TextField(verbose_name='توضیحات شرکت')),
                ('company_logo', models.ImageField(upload_to='images/main/company/', verbose_name='لوگو شرکت')),
                ('company_address', models.CharField(max_length=100, verbose_name='آدرس شرکت')),
                ('company_email', models.EmailField(max_length=100, verbose_name='ایمیل شرکت')),
                ('company_phone', models.CharField(max_length=20, verbose_name='شماره تماس شرکت')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات شرکت',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/main/slider/', verbose_name='فایل تصویر')),
                ('image_title', models.CharField(max_length=100, verbose_name='عنوان تصویر')),
                ('image_description', models.CharField(max_length=100, verbose_name='توضیحات تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر',
                'verbose_name_plural': 'تصاویر اسلایدر',
            },
        ),
    ]
