# Generated by Django 6.0.5 on 2026-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='نام کاربر')),
                ('user_family', models.CharField(max_length=50, verbose_name='نام خانوادگی کاربر')),
                ('user_email', models.EmailField(max_length=100, verbose_name='ایمیل کاربر')),
                ('message_title', models.CharField(max_length=100, verbose_name='موضوع پیام')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پیام')),
                ('is_seen', models.BooleanField(default=False, verbose_name='وضعیت بررسی پیام')),
            ],
            options={
                'verbose_name': 'پیام کاربر',
                'verbose_name_plural': 'پیام های کاربران',
            },
        ),
    ]
