# Generated by Django 6.0.5 on 2026-07-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_title', models.CharField(max_length=50, verbose_name='عنوان تبلیغ')),
                ('advertisement_description', models.TextField(verbose_name='متن تبلیغ')),
                ('advertisement_picture', models.ImageField(upload_to='images/main/advertisement/', verbose_name='تصویر تبلیغ')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال بودن')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
    ]
